title: HH / Python
description: Haaga-Helia / Python-ohjelmointi (SOF004AS2A)
theme: just-the-docs
repository: python-ohjelmointi/python-ohjelmointi.github.io
url: https://python-ohjelmointi.github.io/

aux_links:
  Opintojaksokuvaus: https://opinto-opas.haaga-helia.fi/course_unit/SOF004AS2A

permalink: /:title/

plugins:
  - jekyll-target-blank

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  esim:
    title: Esimerkki
    color: green
  huom:
    title: 💡 Huomio!
    color: green
  vinkki:
    title: Vinkki
    color: green

gh_edit_link: true
gh_edit_link_text: "📝 Muokkaa tätä sivua GitHubissa"
gh_edit_repository: "https://github.com/python-ohjelmointi/python-ohjelmointi.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
